### ISSUE TITLE
Unsubscribe feature

### ISSUE THREAD

**Issue by Bartvds** [DefinitelyTyped/dt-review-tool#4]
@vvakame Is there a way to unsubscribe from these approval messages? 

I'm original author for a ton of definitions but I haven't really touched TypeScript in about 2 years (doing Python now) so I cannot really review anything. I can ignore the github notifications but PR's shouldn't really wait for me.

Maybe this repo could have a file with in-active usernames we can PR against or something.

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/dt-review-tool/blob/master/lib/index.ts#L123
Here is it.
I'll add your name to here. please wait.
