### ISSUE TITLE
Request to no longer be notified for z-schema PRs

### ISSUE THREAD

**Issue by job13er** [DefinitelyTyped/dt-review-tool#6]
It was brought to my attention that I can request here to no longer be notified of PRs to the type definition I added a while back. I'm no longer using typescript, so I wouldn't be the best person to review changes to those typings anymore:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14005

Thanks.

**Comment by vvakame** [comment]
I added your name to inactive user list.
thank you for your contributions.
