### ISSUE TITLE
Should support multiline "Definitions by"

### ISSUE THREAD

**Issue by tkrotoff** [DefinitelyTyped/dt-review-tool#7]
Example:

```TypeScript
// Type definitions for React Router 4.0
// Project: https://github.com/ReactTraining/react-router
// Definitions by: Sergey Buturlakin <https://github.com/sergey-buturlakin>
//                 Yuichi Murata <https://github.com/mrk21>
//                 Václav Ostrožlík <https://github.com/vasek17>
//                 Nathan Brown <https://github.com/ngbrown>
//                 Alex Wendland <https://github.com/awendland>
//                 Kostya Esmukov <https://github.com/KostyaEsmukov>
//                 John Reilly <https://github.com/johnnyreilly>
//                 Karol Janyst <https://github.com/LKay>
//                 Dovydas Navickas <https://github.com/DovydasNavickas>
//                 Tanguy Krotoff <https://github.com/tkrotoff>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.2
```

=> `can't parse definition header...`

**Comment by vvakame** [comment]
Sorry I was late.
take a look this issue today.

**Comment by vvakame** [comment]
umm... this is https://github.com/DefinitelyTyped/definition-header matter...

**Comment by vvakame** [comment]
I am not familiar with persimmon... it is difficult.
I will continue tomorrow.
https://github.com/DefinitelyTyped/definition-header/tree/fix-dt-review-tool-issue7
https://github.com/DefinitelyTyped/definition-header/blob/3b5ce1a48467bcf9e27bdc32bc507d0f88b41a84/src/parser/lax.ts#L124-L134

**Comment by Bartvds** [comment]
@vvakame I think the issue is the lack of commas. So try to change the separatorComma for separatorOptComma (it is already defined earlier) or try to modify a new separator.

**Comment by vvakame** [comment]
@Bartvds I tried it and got good result of testing 👍 
but `failed 48 and passed 2989 of 3037 tests (2361ms)` left still... 😿 
Could you take a look this branch? https://github.com/DefinitelyTyped/definition-header/tree/fix-dt-review-tool-issue7

**Comment by Bartvds** [comment]
I'm not setup for TS anymore, but a glance at Travis log makes me think the error report is off by a line: the arrow seems to point at the dot in the first line (even though it reports line 2).

So two things: 

1) I feel it doesn't split lines correctly, so it reports wrong line (does it strip/split UTF-8 BOM marker, weird unicode whitespace and all line-ends?).

2) All the errors have a format with for example `foo (bar) 1.1` with the arrow pointing at the first dot. Seems suspicious, maybe this is not supported in current parser? Does it expect `foo 1.1 (bar)` instead?

Anyway, parssimmon is cool idea but a big hassle to use, maybe you should throw it out for real parser like PegJS (if you understand those).
